// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Augments a module with additional tasks and adjusted time estimates based on a prompt.
 *
 * - augmentTasks - A function that handles the task augmentation process.
 * - AugmentTasksInput - The input type for the augmentTasks function.
 * - AugmentTasksOutput - The return type for the augmentTasks function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';

const AugmentTasksInputSchema = z.object({
  moduleDescription: z
    .string()
    .describe('The description of the module to augment.'),
  existingTasks: z
    .string()
    .describe('The existing tasks in the module, as a string.'),
  prompt: z.string().describe('A prompt to guide the addition of more tasks to the current module and adjust task times.'),
  apiKey: z.string().optional().describe('Optional Gemini API Key provided by the user.'),
});
export type AugmentTasksInput = z.infer<typeof AugmentTasksInputSchema>;

const AugmentTasksOutputSchema = z.object({
  augmentedTasks: z
    .string()
    .describe('The augmented tasks with adjusted time estimates.'),
});
export type AugmentTasksOutput = z.infer<typeof AugmentTasksOutputSchema>;

export async function augmentTasks(input: AugmentTasksInput): Promise<AugmentTasksOutput> {
  return augmentTasksFlow(input);
}

const prompt = ai.definePrompt({
  name: 'augmentTasksPrompt',
  model: googleAI.model('gemini-2.5-flash'),
  input: { schema: AugmentTasksInputSchema },
  output: { schema: AugmentTasksOutputSchema },
  prompt: `You are a project management assistant. You will be provided with a module description, a list of existing tasks, and a prompt.
Your job is to augment the existing tasks with new tasks and adjusted time estimates based on the prompt.

Module Description: {{{moduleDescription}}}
Existing Tasks: {{{existingTasks}}}
Prompt: {{{prompt}}}

Return the augmented tasks with adjusted time estimates as a string.
`,
});

const augmentTasksFlow = ai.defineFlow(
  {
    name: 'augmentTasksFlow',
    inputSchema: AugmentTasksInputSchema,
    outputSchema: AugmentTasksOutputSchema,
  },
  async (input) => {
    if (input.apiKey) {
      console.log("Using custom API key for augmentTasks");

      const response = await ai.generate({
        model: googleAI.model('gemini-2.5-flash'),
        prompt: `You are a project management assistant. You will be provided with a module description, a list of existing tasks, and a prompt.
Your job is to augment the existing tasks with new tasks and adjusted time estimates based on the prompt.

Module Description: ${input.moduleDescription}
Existing Tasks: ${input.existingTasks}
Prompt: ${input.prompt}

Return the augmented tasks with adjusted time estimates as a string.
`,
        config: {
          apiKey: input.apiKey, // Use a different API key for this request
        },
        output: { schema: AugmentTasksOutputSchema },
      });
      return response.output!;
    }

    // Default path
    const { output } = await prompt(input);
    return output!;
  }
);
